val commonMain by getting {
    dependencies {
        api(libs.compose.foundation)
        api(libs.compose.material3)
        api(libs.compose.runtime)
        api(libs.compose.ui)
        api(libs.material.icons.core)
        api(libs.kotlin)
        api(libs.kotlin.reflect)
        api(libs.kotlinx.coroutines)
        api(libs.kotlinx.datetime)
        api(libs.kotlinx.io.core)
        api(libs.kotlinx.serialization.json)
        api(libs.ksoup)

        // ✅ KTOR（统一 CIO）
        api(libs.ktor.client.core)
        api(libs.ktor.client.cio)
        api(libs.ktor.client.content.negotiation)
        api(libs.ktor.serialization.kotlinx.json)
        api(libs.ktor.client.auth)

        api(libs.moko.resources)
        api(libs.moko.resources.compose)
        api(libs.multiplatformSettings)
        api(libs.multiplatformSettings.noArg)
        api(libs.richeditor.compose)
        api(libs.semver)
        api(libs.filekit.core)
        api(libs.filekit.dialogs.compose)
        api(libs.kmpfile)
        api(libs.kmpplatform)
        api(libs.zwander.composedialog)
        api(libs.zwander.materialyou)
        api(libs.csv)
        api(libs.cryptography.core)
        api(libs.kotlinx.crypto.crc32)
        api(libs.kotlinx.atomicfu)
        api(libs.androidx.performance.annotation)
        api(libs.xmlbuilder)
        api(libs.ketch.core)
        api(libs.ketch.ktor)
        api(libs.ketch.sqlite)
    }
}
